server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : car-service
          #uri: http://localhost:8045
          uri: lb://car-service
          predicates:
            - Path=/cars/**
#        - id: cart-service
#          #uri: http://localhost:8050
#          uri: lb://CART-SERVICE
#          predicates:
#            - Path=/cart/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka